// <auto-generated />
using System;
using HorasExtras.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HorasExtras.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230808035228_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HorasExtras.Domain.Entities.AprobacionHorasExtras", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AprobacionLider")
                        .HasColumnType("int");

                    b.Property<int>("AprobacionRRHH")
                        .HasColumnType("int");

                    b.Property<Guid?>("AprobadorRRHHId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LiderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MotivoLider")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MotivoRRHH")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AprobadorRRHHId");

                    b.HasIndex("LiderId");

                    b.ToTable("AprobacionHorasExtras");
                });

            modelBuilder.Entity("HorasExtras.Domain.Entities.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LiderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LiderId");

                    b.ToTable("Area");
                });

            modelBuilder.Entity("HorasExtras.Domain.Entities.Colaborador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Colaborador");
                });

            modelBuilder.Entity("HorasExtras.Domain.Entities.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("HorasExtras.Domain.Entities.SolicitudHorasExtras", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AprobacionHorasExtrasId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColaboradorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Dias")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AprobacionHorasExtrasId");

                    b.HasIndex("ColaboradorId");

                    b.ToTable("SolicitudHorasExtras");
                });

            modelBuilder.Entity("HorasExtras.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("ClaveHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("HorasExtras.Domain.Entities.AprobacionHorasExtras", b =>
                {
                    b.HasOne("HorasExtras.Domain.Entities.Colaborador", "AprobadorRRHH")
                        .WithMany()
                        .HasForeignKey("AprobadorRRHHId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HorasExtras.Domain.Entities.Colaborador", "Lider")
                        .WithMany()
                        .HasForeignKey("LiderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AprobadorRRHH");

                    b.Navigation("Lider");
                });

            modelBuilder.Entity("HorasExtras.Domain.Entities.Area", b =>
                {
                    b.HasOne("HorasExtras.Domain.Entities.Colaborador", "Lider")
                        .WithMany()
                        .HasForeignKey("LiderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Lider");
                });

            modelBuilder.Entity("HorasExtras.Domain.Entities.Colaborador", b =>
                {
                    b.HasOne("HorasExtras.Domain.Entities.Area", "Area")
                        .WithMany("Empleados")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorasExtras.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HorasExtras.Domain.Entities.SolicitudHorasExtras", b =>
                {
                    b.HasOne("HorasExtras.Domain.Entities.AprobacionHorasExtras", "AprobacionHorasExtras")
                        .WithMany()
                        .HasForeignKey("AprobacionHorasExtrasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HorasExtras.Domain.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AprobacionHorasExtras");

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("HorasExtras.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("HorasExtras.Domain.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("HorasExtras.Domain.Entities.Area", b =>
                {
                    b.Navigation("Empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
